CREATE DATABASE lefutgoat;
USE lefutgoat;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(100),
 password VARCHAR(100)
);

CREATE TABLE players (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 goals INT
);